title: "Aaron Rofe – Applied Data Science Portfolio"
description: "M.S. Applied Data Science Portfolio – Syracuse University (Fall 2025)"
theme: jekyll-theme-cayman

markdown: kramdown
kramdown:
  input: GFM

# Load custom stylesheet
sass:
  style: compressed

include:
  - assets/css/style.css

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - LICENSE
